### ISSUE TITLE
Error when first join

### ISSUE THREAD

**Issue by Greatie** [ptown2/GLMVS#1]
I get this error when I join my own server:

[ERROR] addons/glmvs/lua/sh_addmaps.lua:1: attempt to index global 'GLMVS' (a nil value)
1. unknown - addons/glmvs/lua/sh_addmaps.lua:1
2. include - [C]:-1
3. unknown - addons/glmvs/lua/autorun/autorun.lua:18

[ERROR] addons/glmvs/lua/cl_init.lua:9: attempt to index global 'GLMVS' (a nil value)
1. unknown - addons/glmvs/lua/cl_init.lua:9
2. include - [C]:-1
3. unknown - addons/glmvs/lua/autorun/autorun.lua:19

Fresh install, running Zombie Survival.

To reproduce: Join a server with GLMVS is my best guess.

**Comment by ptown2** [comment]
I'm already dealing with this bug, the module isn't including/loading for the client by some unexpected reason. But the server is having no issues whatsoever.

Might need to load the modules differently...

EDIT:
Listen Servers are 100% working fine for both server and client (as the host, not sure when other players are around.)
Dedicated Servers are working server-sided, client-sided is nothing.

**Comment by Greatie** [comment]
Alright, cool, seems pretty minor anyways.

**Comment by ptown2** [comment]
This bug has been fixed, just let me fix another bug that wasn't mentioned (server-sided, but doesn't ultimately affect the addon entirely) and some other bug to iron it out for now.

Expected release might be one to two hours.

**Comment by ptown2** [comment]
Uploaded fix, this bug did some serious breakage and should work fine on dedicated servers. (Quick tested it and worked fine.)
