### ISSUE TITLE
GLMVS does not pick up PNG files

### ISSUE THREAD

**Issue by Greatie** [ptown2/GLMVS#2]
It downloads them, yeah, but at the map list, the icons doesn't show up. Icons are at 150 by 150, they're PNG, and they're in the garrysmod/maps folder.

**Comment by ptown2** [comment]
Forgot that Garry's Mod downloads the files then saves in the garrysmod/download folder, I'll make it that it loads the image from there too.

**Comment by ptown2** [comment]
Fixed this issue a long time ago, going to publish the new version in a few minutes. Introduces new features than ever before.
